name: GitHub Contribution Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: DenverCoder1/github-readme-snake-action@main
        with:
          username: cabdikariim242
          color: 9966EB
          background: 0,0,0,0
          size: 25
          square: true

      - name: Commit SVG
        run: |
          git add snake.svg
          git commit -m "Update Snake" || echo "Nothing to commit"
          git push
